### ISSUE TITLE
Cannot install Zope 4 with ZServer following installation documentation

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/ZServer#19]
In order to reproduce zopefoundation/Zope#665 with a clean Zope installation, I tried to install Zope 4 with ZServer following the documenation at https://zope.readthedocs.io/en/latest/INSTALL.html and https://zope.readthedocs.io/en/2.13/INSTALL-buildout.html#creating-a-zope-instance

Result:
```
jugmac00@jugmac00-XPS-13-9370:~/Projects/zserver-test$ bin/mkzopeinstance
Please choose a directory in which you'd like to install
Zope "instance home" files such as database files, configuration
files, etc.

Directory: instance
Please choose a username and password for the initial user.
These will be the credentials you use to initially manage
your new Zope instance.

Username: admin
Password: 
Verify password: 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named Zope2
```

Step by step...
```
jugmac00@jugmac00-XPS-13-9370:~/Projects$ mkdir zserver-test
jugmac00@jugmac00-XPS-13-9370:~/Projects$ cd zserver-test/
jugmac00@jugmac00-XPS-13-9370:~/Projects/zserver-test$ virtualenv .venv -p /usr/bin/python2.7
jugmac00@jugmac00-XPS-13-9370:~/Projects/zserver-test$ . .venv/bin/activate
(.venv) jugmac00@jugmac00-XPS-13-9370:~/Projects/zserver-test$ pip install zc.buildout

[buildout]
extends =
    https://zopefoundation.github.io/Zope/releases/4.1/versions-prod.cfg
parts =
    zopeinstance

[zopeinstance]
recipe = plone.recipe.zope2instance
eggs =
    Products.TemporaryFolder
    ZServer
user = admin:adminpassword
http-address = 8080
wsgi = off

(.venv) jugmac00@jugmac00-XPS-13-9370:~/Projects/zserver-test$ buildout

jugmac00@jugmac00-XPS-13-9370:~/Projects/zserver-test$ bin/mkzopeinstance
Please choose a directory in which you'd like to install
Zope "instance home" files such as database files, configuration
files, etc.

Directory: instance
Please choose a username and password for the initial user.
These will be the credentials you use to initially manage
your new Zope instance.

Username: admin
Password: 
Verify password: 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named Zope2
```

**Comment by icemac** [comment]
The shown error message does not mean that creating an instance had an error, it is only an internal message which should be suppressed.

**Comment by icemac** [comment]
See https://github.com/zopefoundation/Zope/commit/eed8f0cf2d7a598d4fa969ab7e8b008de10a8cee as the commit introducing the fix in the Zope repository.

**Comment by jugmac00** [comment]
@icemac  I am not sure what this means... is this issue fixed with your linked commit?

**Comment by icemac** [comment]
@jugmac00 I think that the liked commit has to be ported to ZServer as it has its own copy of the code.
